#internet|local
osmLocation: local 

 # "http://download.geofabrik.de/europe/germany-latest.osm.pbf
 # 
 #"http://download.geofabrik.de/europe/germany/baden-wuerttemberg-latest.osm.pbf"
osmFilename: "res/baden-wuerttemberg-latest.osm.pbf"

# 1 parse the osm files and write to file for reuse
# 0 use existing parsed data
osmParse: 0

#json|protobuf are valid  (json not recommended)
outputType: "protobuf"

outputFilename: "res/graph.bin"


# 1 Info| 2 Warning | 3 Error
logLevel: 0

gridXSize: 100
gridYSize: 100


infoFilename: "res/metaInfo.json"
fuelStationsFilename: "res/fuelStations.json"
