version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - /data/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432

  dpage:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 8080:80
